services:
  - type: web
    name: edtech-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -b 0.0.0.0:10000"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
